

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - DATABASE_URL=postgres://db_user:pass@db:5432/app_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user"]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  backend:
    driver: bridge


